# Generated by Django 3.2.25 on 2024-07-02 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_type', models.CharField(max_length=200)),
                ('skill_desc', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutMe.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exp_name', models.CharField(max_length=200)),
                ('exp_dur', models.CharField(max_length=200)),
                ('exp_desc', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutMe.person')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edu_name', models.CharField(max_length=200)),
                ('edu_dur', models.CharField(max_length=200)),
                ('edu_desc', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutMe.person')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('cert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=200)),
                ('cert_desc', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutMe.person')),
            ],
        ),
    ]
