# Generated by Django 3.2.25 on 2024-07-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
