# Generated by Django 3.2.25 on 2024-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe', '0002_auto_20240702_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
