# Generated by Django 3.2.25 on 2024-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='linkedinh',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
